-- creating Table for User 

CREATE TABLE User (
	User_ID	INT	NOT NULL,
	Firstname VARCHAR(20) NOT NULL,
	Lastname VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_User
		PRIMARY KEY (User_ID)

		)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- creating Table for Tool
	
CREATE TABLE Tool (
	Tool_ID	INT	NOT NULL,
	Toolname VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_Tools
		PRIMARY KEY (Tool_ID)

		)ENGINE=InnoDB DEFAULT CHARSET=latin1;
	
	
-- creating Table for Verify
	
CREATE TABLE Verify (
	
	User_ID	INT	NOT NULL,
	Tool_ID	INT	NOT NULL,
	
	CONSTRAINT PK_Verify
		PRIMARY KEY (User_ID,Tool_ID),
		
	CONSTRAINT FK_Verify_User
		FOREIGN KEY (User_ID) REFERENCES User(User_ID)
		ON UPDATE CASCADE,
		
	CONSTRAINT FK_Verify_Tool
		FOREIGN KEY (Tool_ID) REFERENCES Tool(Tool_ID)
		ON UPDATE CASCADE
		)ENGINE=InnoDB DEFAULT CHARSET=latin1;
	
-- creating Table for History
	
CREATE TABLE History (
	
	User_ID	INT	NOT NULL,
	Tool_ID	INT	NOT NULL,
	Timestamp DATETIME NOT NULL,
	
	CONSTRAINT Pk_His
		PRIMARY KEY (User_ID,Tool_ID),
		
	CONSTRAINT FK_His_User
		FOREIGN KEY (User_ID) REFERENCES User(User_ID)
		ON UPDATE CASCADE,
		
	CONSTRAINT FK_His_Tool
		FOREIGN KEY (Tool_ID) REFERENCES Tool(Tool_ID)
		ON UPDATE CASCADE
		
	)ENGINE=InnoDB DEFAULT CHARSET=latin1;
